### ISSUE TITLE
softmax not implemented on CPU

### ISSUE THREAD

**Issue by hjk41** [dmlc/minerva#12]
Jiaxing's intern is working on LSTM on CPU. He need softmax.

**Comment by hotpxl** [comment]
I can do this

**Comment by jermainewang** [comment]
You might want to look at torch's softmax implementation:
https://github.com/torch/nn/blob/master/generic/SoftMax.c

On Thu, Mar 19, 2015 at 4:44 AM, Hot.PxL <notifications@github.com> wrote:

> I can do this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/12#issuecomment-83423370>
> .
>



-- 
Minjie Wang
*New York University | Computer Science*
715 Broadway, New York, NY, 10009

**Comment by jermainewang** [comment]
Is softmax on the master branch now?

**Comment by sneakerkg** [comment]
I think it's on the lstm branch. Could we merge it now?


2015-04-20 11:44 GMT+08:00 Minjie Wang <notifications@github.com>:

**Comment by hjk41** [comment]
merged into master
