### ISSUE TITLE
Tutorial, API Documentation?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/minerva#13]
Hi ,
Is there tutorial for the API in the project ? I've found only the sample code (mnist_mlp, mnist_cnn....)

Thanks!

**Comment by hjk41** [comment]
copying Minjie.

Minjie, could we share the Python docs now? We can wait sometime for the
c++ docs.

On Sun, Mar 22, 2015 at 6:36 AM, Kublai-Jing <notifications@github.com>
wrote:

> Hi ,
> Is there tutorial for the API in the project ? I've found only the sample
> code (mnist_mlp, mnist_cnn....)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/13>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by jermainewang** [comment]
Hi,

We are working on that. And it will soon be released (in one week). Sorry for the inconvenience.

**Comment by jermainewang** [comment]
Hi Kublai-Jing,

Sorry for the long wait. The documents and tutorials are finally here. Hope it's not too late.

Tutorials: https://github.com/dmlc/minerva
API Document: http://minerva-developers.github.io/minerva-doc/index.html

Best regards,
Minjie
