### ISSUE TITLE
self-defined elemwise function on GPU ?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/minerva#14]
Hi,

I've looked at the NIPS paper and the code snippet there presents a very convenient way of defining elem-wise function:

float Sigmoid(float x){
    return 1.0 / (1.0 + exp(-x));
}

Then we just do:

Matrix z = (V * y + c).Map(&Sigmoid);

 However, the current version seems to be completely different from the one presented in the paper, so I wonder why ? Or how do I achieve such goal in the current version of the code easily (instead of writing cuda code myself).  Sorry, just start to look at this project recently so I might've missed some context

Thanks

**Comment by sneakerkg** [comment]
Hi,

We are involving our interface so there might be some differences. And our
python interface has become similar with numpy. So with your example, we
can just write:

x= V*y+c
z= 1 / (1 + ele.exp( 0 - x)) or z = ele.sigmoid(x)

We've already built in some element-wise functions. You can refer to
https://github.com/minerva-developers/minerva/blob/master/owl/owl/elewise.py.
And the combination of those functions with +-*/ can achieve more complex
ele-wise operations.

You could have a try and tell whether the interface can fulfill your need.
If not, we'll be appreciated if you can provide the operations you need,
we'll consider add them into later version.

Thanks,
Tianjun


2015-03-23 10:20 GMT+08:00 Kublai-Jing <notifications@github.com>:

**Comment by Kublai-Jing** [comment]
Hi Tianjun,
I am actually trying to do similar thing with ReLUbackward where I want to perform elemwise test of positive number: something like this in numpy:

X = (X > 0);

and I it seems that currently this type of operation on GPU is not supported (?)

p.s. is there a plan for integrating PS with numpy later ? I just started to use Minerva and haven't decided whether I should pick C++ or python for my project

Thanks for the reply !

**Comment by sneakerkg** [comment]
Hi Kublai,

For your request: X = (X > 0), would "ele.relu(X) / X" work the way you
want? (If there's 0 in X, this could be problematic, you may need add some
epsilon to prevent that. It's better to implement a new element-wise
operator, but this will surely involve cuda coding).

And for the PS. There's some guys working on integrating PS with numpy. But
it may take some time to release.

Thanks,
Tianjun

2015-03-23 10:48 GMT+08:00 Kublai-Jing <notifications@github.com>:
