### ISSUE TITLE
Can't get libminervaps.a

### ISSUE THREAD

**Issue by fishbone** [dmlc/minerva#19]
I'm following the instructions to integrate minerva with parameter server. But I always fail to get libminervaps.a. I have some confusions here. I don't understand "then compile with make minerva". What does this mean, should I make under the parameter server sources or under minerva? If under parameter server directory, it says not such target. And under minerva directory, it will not give me libminervaps.a. I'm sure that I run configure with parameter enabled.

**Comment by hjk41** [comment]
Hi,

libminervaps.a is built with the "parameter server" project (
https://github.com/mli/parameter_server). We are working with the parameter
server guys on a new version of the integration which would support Python
interface. Please give me some time and I will revise the Minerva wiki
according to the latest version of code.

On Tue, Mar 31, 2015 at 6:07 AM, Yi Cheng <notifications@github.com> wrote:

> I'm following the instructions to integrate minerva with parameter server.
> But I always fail to get libminervaps.a. I have some confusions here. I
> don't understand "then compile with make minerva". What does this mean,
> should I make under the parameter server sources or under minerva? If under
> parameter server directory, it says not such target. And under minerva
> directory, it will not give me libminervaps.a. I'm sure that I run
> configure with parameter enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/19>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by fishbone** [comment]
Now I know that it's build under parameter server directory. 
But when I execute  "make minvera" under that directory it said no such target. 
If it's convenient for you, could you tell me how to get libminervaps.a? I have built the parameter server.
Now I don't need the script for python.

**Comment by hjk41** [comment]
Hi,

Please checkout the parameter server code from here:
https://github.com/hjk41/parameter_server
Under the parameter server folder, use "make minerva" and you should be
able to get libminervaps.a under parameter_server/build. Copy that file to
minerva/deps/lib

Checkout the minerva code from:
https://github.com/minerva-developers/minerva.git
    git checkout ps
    ./configure --enable-ps
    cd release
    make -j

You should be able to get mnist_mlp_ps under release/apps

On Wed, Apr 1, 2015 at 4:28 AM, Yi Cheng <notifications@github.com> wrote:

> Now I know that it's build under parameter server directory.
> But when I execute "make minvera" under that directory it said no such
> target.
> If it's convenient for you, could you tell me how to get libminervaps.a? I
> have built the parameter server.
> Now I don't need the script for python.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minerva-developers/minerva/issues/19#issuecomment-88234003>
> .
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by fishbone** [comment]
That's great, thank you.
