### ISSUE TITLE
Is there a functional google groups or email address for this project?

### ISSUE THREAD

**Issue by o1lo01ol1o** [dmlc/minerva#23]
The emails I've sent 

minerva-support@googlegroups.com

bounce back.

My question is about recurrent functions and BPTT; does the C++/cuda codebase currently have implementations?

**Comment by hjk41** [comment]
hi,

We have a running example in owl/apps/lstm. It is written in Python, but
you should also be able to rewrite it in C++ except for the NumPy calls,
the syntax of C++ and Python interface are almost identical.

I have just sent a test email to the minerva-support@googlegroups.com group
and it seems to work fine. Could you try it again?

Thanks

On Sun, May 3, 2015 at 11:21 AM, o1lo01ol1o <notifications@github.com>
wrote:

> The emails I've sent
>
> minerva-support@googlegroups.com
>
> bounce back.
>
> My question is about recurrent functions and BPTT; does the C++/cuda
> codebase currently have implementations?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/23>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hotpxl** [comment]
@hjk41 probably the googlegroup is not accepting emails from people outside of it?

**Comment by hjk41** [comment]
I tried sending an email with my other account and it works just fine.

On Mon, May 4, 2015 at 2:35 PM, Yutian Li <notifications@github.com> wrote:

> @hjk41 <https://github.com/hjk41> probably the googlegroup is not
> accepting emails from people outside of it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/23#issuecomment-98597429>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by o1lo01ol1o** [comment]
Strange, this last email appears to have gone through. 

Though I still can't seem to find the actual mailing list in google groups . . . 

Anyway, I'll look through the lstm code, thanks!

**Comment by hotpxl** [comment]
I've enabled public access to the google group. It should work anyways now.
