### ISSUE TITLE
C++ Documentation?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/minerva#27]
IS there a plan to release C++ API docs?

For instance, I saw concat function in python, is there a equivalent one in C++?

Thanks,
Kublai

**Comment by jermainewang** [comment]
Hi Kublai,

There is no recent plan to release C++ API docs yet. But I will try add a python <-> C++ API correspondence in Owl API cheatsheet.

For your question on concat function, there is indeed a C++ one [here](https://github.com/dmlc/minerva/blob/master/minerva/narray/narray.h#L75). In fact, most of the python array api has its correspondence in C++.

Best,
Minjie

**Comment by Kublai-Jing** [comment]
Thanks a lot Minjie !
-- did not look into .h file :)
