### ISSUE TITLE
Does installation of Own module require dmlc? 

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#29]
I followed the *Build Owl module* instruction here (https://github.com/dmlc/minerva/wiki/Install-Minerva) but the build fails 

```
minerva/narray/narray.h:3:26: fatal error: dmlc/logging.h: No such file or directory
 #include <dmlc/logging.h>
```

**Comment by hjk41** [comment]
Hi Zeron,

Did you pull the latest code? The building script has been changed
recently, it should be able to pull dmlc related stuff automatically.

On Fri, Jun 12, 2015 at 3:35 PM, zer0n <notifications@github.com> wrote:

> I followed the *Build Owl module* instruction here (
> https://github.com/dmlc/minerva/wiki/Install-Minerva) but the build fails
>
> minerva/narray/narray.h:3:26: fatal error: dmlc/logging.h: No such file or directory
>  #include <dmlc/logging.h>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/29>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zer0n** [comment]
Yes. In fact, I just `git clone https://github.com/dmlc/minerva` recently. I don't see `dmlc` anywhere in the `minerva` repo.

**Comment by hjk41** [comment]
Can you do "cd release && make VERBOSE=1 &>log" and send the log to us?

On Fri, Jun 12, 2015 at 4:03 PM, zer0n <notifications@github.com> wrote:

> Yes. In fact, I just git clone https://github.com/dmlc/minerva recently.
> I don't see dmlc anywhere in the minerva repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/29#issuecomment-111402736>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zer0n** [comment]
It's the same problem as reported in https://github.com/dmlc/minerva/issues/30
