### ISSUE TITLE
Can't build apps

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#30]
Does minerva work with CUDA 7? I installed CUDA 7 and all the samples worked well but I cannot build minerva apps with errors like `undefined reference to curandGenerateNormal`.

```
...
-- cmake generator: Unix Makefiles
-- cmake build tool: /usr/bin/make
-- cmake build type: Release
-- Found cuDNN (include: ~/cudnn2, library: ~/cudnn2/libcudnn.so)
-- Found BLAS (include: /usr/include, library: /opt/openblas/lib/libcblas.so)
-- build C++ applications              -- 1                                                                                                                                                         [9/1758]
-- build unit tests                    -- 0
-- build cpu-only version              -- 0
-- build with parameter server support -- 0
-- build with BLAS library for CPU     -- 1
-- Build CXX Applications:
--   mnist_cnn_2gpu
--   mnist_mlp
--   main
--   mnist_cnn
-- Configuring done
-- Generating done
-- Build files have been written to: ~/minerva/release
[ 16%] Built target gflags
[ 32%] Built target dmlc-core
[ 32%] Built target third-party
Linking CXX shared library ../lib/libminerva.so
[ 91%] Built target minerva
Linking CXX executable main
../lib/libminerva.so: undefined reference to `curandGenerateNormal'
../lib/libminerva.so: undefined reference to `curandSetPseudoRandomGeneratorSeed'
../lib/libminerva.so: undefined reference to `curandCreateGenerator'
```

Here's my `config.in` file
```
BUILD_DIR=release
CXX=g++
CC=gcc
CXXFLAGS=
CUDA_ROOT=/usr/local/cuda
CUDNN_ROOT=/home/zer0n/cudnn2
BUILD_TYPE=Release
BUILD_OWL=0
BUILD_CXX_APPS=1
BUILD_TESTS=0
BUILD_WITH_PS=0
PS_ROOT=
BUILD_CPU_ONLY=0
BUILD_WITH_BLAS=1
BLAS_ROOT=/opt/openblas
```
I have successfully installed `Caffe` with CUDA 7 using [this instruction](https://github.com/BVLC/caffe/wiki/Install-Caffe-on-EC2-from-scratch-(Ubuntu,-CUDA-7,-cuDNN)) tho.

**Comment by zer0n** [comment]
Another piece of information, I'm running Ubuntu 12.04. I don't see how the linking error above has anything to do with Ubuntu version though but shouting out just in case they are related.

**Comment by zer0n** [comment]
Posting verbose log 

```
...
make[2]: Entering directory `/home/zer0n/minerva/release'
cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/third_party /home/zer0n/minerva/release /home/zer0n/minerva/release/third_party /home/zer0n/minerva/release/third_party/CMakeFiles/third-party.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/zer0n/minerva/release'
make -f third_party/CMakeFiles/third-party.dir/build.make third_party/CMakeFiles/third-party.dir/build
make[2]: Entering directory `/home/zer0n/minerva/release'
make[2]: Nothing to be done for `third_party/CMakeFiles/third-party.dir/build'.
make[2]: Leaving directory `/home/zer0n/minerva/release'
/usr/bin/cmake -E cmake_progress_report /home/zer0n/minerva/release/CMakeFiles
[ 32%] Built target third-party
make -f minerva/CMakeFiles/minerva.dir/build.make minerva/CMakeFiles/minerva.dir/depend
make[2]: Entering directory `/home/zer0n/minerva/release'
cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/minerva /home/zer0n/minerva/release /home/zer0n/minerva/release/minerva /home/zer0n/minerva/release/minerva/CMakeFiles/minerva.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/zer0n/minerva/release'
make -f minerva/CMakeFiles/minerva.dir/build.make minerva/CMakeFiles/minerva.dir/build
make[2]: Entering directory `/home/zer0n/minerva/release'
make[2]: Nothing to be done for `minerva/CMakeFiles/minerva.dir/build'.
make[2]: Leaving directory `/home/zer0n/minerva/release'
/usr/bin/cmake -E cmake_progress_report /home/zer0n/minerva/release/CMakeFiles  18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
[ 91%] Built target minerva
make -f apps/CMakeFiles/main.dir/build.make apps/CMakeFiles/main.dir/depend
make[2]: Entering directory `/home/zer0n/minerva/release'
cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/apps /home/zer0n/minerva/release /home/zer0n/minerva/release/apps /home/zer0n/minerva/release/apps/CMakeFiles/main.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/zer0n/minerva/release'
make -f apps/CMakeFiles/main.dir/build.make apps/CMakeFiles/main.dir/build
make[2]: Entering directory `/home/zer0n/minerva/release'
Linking CXX executable main
cd /home/zer0n/minerva/release/apps && /usr/bin/cmake -E cmake_link_script CMakeFiles/main.dir/link.txt --verbose=1
/usr/lib/ccache/g++   -Wall -fPIC -march=native -O2 -mtune=native -mssse3 -std=c++11 -DNDEBUG    CMakeFiles/main.dir/main.cpp.o  -o main -rdynamic ../lib/libminerva.so -lpthread ../third_party/lib/libgflags.a ../third_party/lib/libdmlc.a /usr/local/cuda/lib64/libcublas.so /usr/local/cuda/lib64/libcudart.so -lcuda /usr/local/cuda/lib64/libcublas.so /home/zer0n/cudnn2/libcudnn.so -lpthread ../third_party/lib/libgflags.a ../third_party/lib/libdmlc.a /opt/openblas/lib/libcblas.so -Wl,-rpath,/home/zer0n/minerva/release/lib:/home/zer0n/cudnn2:/usr/local/cuda/lib64:/opt/openblas/lib
../lib/libminerva.so: undefined reference to `curandGenerateNormal'
../lib/libminerva.so: undefined reference to `curandSetPseudoRandomGeneratorSeed'
../lib/libminerva.so: undefined reference to `curandCreateGenerator'
../lib/libminerva.so: undefined reference to `curandDestroyGenerator'
collect2: error: ld returned 1 exit status
make[2]: *** [apps/main] Error 1
make[2]: Leaving directory `/home/zer0n/minerva/release'
make[1]: *** [apps/CMakeFiles/main.dir/all] Error 2
make[1]: Leaving directory `/home/zer0n/minerva/release'
make: *** [all] Error 2
```

**Comment by hjk41** [comment]
It seems your machine is not downloading dmlc-core at all, which is strange.

Would you mine doing "make clean && make VERBOSE=1 &>log" and send us the
log?


On Fri, Jun 12, 2015 at 4:37 PM, zer0n <notifications@github.com> wrote:

> Posting verbose log
>
> ...
> make[2]: Entering directory `/home/zer0n/minerva/release'
> cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/third_party /home/zer0n/minerva/release /home/zer0n/minerva/release/third_party /home/zer0n/minerva/release/third_party/CMakeFiles/third-party.dir/DependInfo.cmake --color=
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> make -f third_party/CMakeFiles/third-party.dir/build.make third_party/CMakeFiles/third-party.dir/build
> make[2]: Entering directory `/home/zer0n/minerva/release'
> make[2]: Nothing to be done for `third_party/CMakeFiles/third-party.dir/build'.
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> /usr/bin/cmake -E cmake_progress_report /home/zer0n/minerva/release/CMakeFiles
> [ 32%] Built target third-party
> make -f minerva/CMakeFiles/minerva.dir/build.make minerva/CMakeFiles/minerva.dir/depend
> make[2]: Entering directory `/home/zer0n/minerva/release'
> cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/minerva /home/zer0n/minerva/release /home/zer0n/minerva/release/minerva /home/zer0n/minerva/release/minerva/CMakeFiles/minerva.dir/DependInfo.cmake --color=
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> make -f minerva/CMakeFiles/minerva.dir/build.make minerva/CMakeFiles/minerva.dir/build
> make[2]: Entering directory `/home/zer0n/minerva/release'
> make[2]: Nothing to be done for `minerva/CMakeFiles/minerva.dir/build'.
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> /usr/bin/cmake -E cmake_progress_report /home/zer0n/minerva/release/CMakeFiles  18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46
> [ 91%] Built target minerva
> make -f apps/CMakeFiles/main.dir/build.make apps/CMakeFiles/main.dir/depend
> make[2]: Entering directory `/home/zer0n/minerva/release'
> cd /home/zer0n/minerva/release && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/zer0n/minerva /home/zer0n/minerva/apps /home/zer0n/minerva/release /home/zer0n/minerva/release/apps /home/zer0n/minerva/release/apps/CMakeFiles/main.dir/DependInfo.cmake --color=
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> make -f apps/CMakeFiles/main.dir/build.make apps/CMakeFiles/main.dir/build
> make[2]: Entering directory `/home/zer0n/minerva/release'
> Linking CXX executable main
> cd /home/zer0n/minerva/release/apps && /usr/bin/cmake -E cmake_link_script CMakeFiles/main.dir/link.txt --verbose=1
> /usr/lib/ccache/g++   -Wall -fPIC -march=native -O2 -mtune=native -mssse3 -std=c++11 -DNDEBUG    CMakeFiles/main.dir/main.cpp.o  -o main -rdynamic ../lib/libminerva.so -lpthread ../third_party/lib/libgflags.a ../third_party/lib/libdmlc.a /usr/local/cuda/lib64/libcublas.so /usr/local/cuda/lib64/libcudart.so -lcuda /usr/local/cuda/lib64/libcublas.so /home/zer0n/cudnn2/libcudnn.so -lpthread ../third_party/lib/libgflags.a ../third_party/lib/libdmlc.a /opt/openblas/lib/libcblas.so -Wl,-rpath,/home/zer0n/minerva/release/lib:/home/zer0n/cudnn2:/usr/local/cuda/lib64:/opt/openblas/lib
> ../lib/libminerva.so: undefined reference to `curandGenerateNormal'
> ../lib/libminerva.so: undefined reference to `curandSetPseudoRandomGeneratorSeed'
> ../lib/libminerva.so: undefined reference to `curandCreateGenerator'
> ../lib/libminerva.so: undefined reference to `curandDestroyGenerator'
> collect2: error: ld returned 1 exit status
> make[2]: *** [apps/main] Error 1
> make[2]: Leaving directory `/home/zer0n/minerva/release'
> make[1]: *** [apps/CMakeFiles/main.dir/all] Error 2
> make[1]: Leaving directory `/home/zer0n/minerva/release'
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/30#issuecomment-111414702>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zer0n** [comment]
I have sent the log file to the Google discussion group. Thanks.

**Comment by sneakerkg** [comment]
Hi zer0n,

It looks like you can't link to libcurand.so, could you have a check that file is under your cuda folder?

Another thing is may I ask the version of your cmake? You mentioned you're on 12.04, I once met similar problem finding curand for the cmake version is low on 12.04.

Thanks,
Tianjun

**Comment by zer0n** [comment]
Thanks. `Ubuntu 12.04` is indeed the cause of all trouble. I needed to upgrade these packages from source in order to build minerva successfully.
- `cmake`
- `ccache`
