### ISSUE TITLE
./main: symbol lookup error: ./main: undefined symbol: _ZN7minerva13MinervaSystem15CreateCpuDeviceEv

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/minerva#31]
I can successfully run the given c++ sample code, but I ran into this problem when trying to build my own app.

-----------------------------------------
g++ -std=c++11 -DHAS_CUDA  -I./dmlc-core/include/ -I/usr/local/cuda-6.5/include -I./include/ -rdynamic ./libminerva.so -rdynamic ./libcudnn.so main.cpp -o main
-----------------------------------------
 when I run it, it says:
-------------------------
./main: symbol lookup error: ./main: undefined symbol: _ZN7minerva13MinervaSystem15CreateCpuDeviceEv
-------------------------
the main.cpp program is just:

#include <minerva.h>
using namespace std;
using namespace minerva;
int main(int argc, char ** argv){
    MinervaSystem::Initialize(&argc, &argv);
    MinervaSystem& ms = MinervaSystem::Instance();
    uint64_t cpuDevice = ms.CreateCpuDevice();
    ms.SetDevice(cpuDevice);
    return 0;
}

--------------
Which I think is strange.. since I find exactly CreateCpuDeviceEv in the binary "libminerva.so".
I am using CentOS 6.5

**Comment by hotpxl** [comment]
Could you `ldd` on the `main` executable to make sure that it has linked to the correct library?

**Comment by Kublai-Jing** [comment]
Yes... The library is just not properly linked. sovled :)
