### ISSUE TITLE
How is Minerva/Owl different from Theano?

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#33]
What advantages does it have over Theano?

Does Minerva/Owl have automatic differentiation capability that Theano has? 

I had thought that Minerva is more comparable to Caffe but it looks like Minerva is more similar to Theano than it is to Caffe. Is it correct?

**Comment by hjk41** [comment]
Minerva is more like Theano in its interface, more like Caffe in
performance. :-)

On Sun, Jun 14, 2015 at 3:19 AM, zer0n <notifications@github.com> wrote:

> What advantages does it have over Theano?
>
> Does Minerva/Owl have automatic differentiation capability that Theano
> has?
>
> I had thought that Minerva is more comparable to Caffe but it looks like
> Minerva is more similar to Theano than it is to Caffe. Is it correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/33>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
