### ISSUE TITLE
Fast convolution using FFT

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#34]
This paper: [Fast Training of Convolutional Networks through FFTs](http://arxiv.org/abs/1312.5851) shows that FFT-based convolution is faster than convolution-unrolling implementation in CuDNN. 

It's [implemented in Torch](https://research.facebook.com/blog/879898285375829/fair-open-sources-deep-learning-modules-for-torch/)

Has anyone in the Minerva team tried this approach?

**Comment by jermainewang** [comment]
Hi,

The FFT algorithm is fast *in some situation*. So to achieve the best performance, you need to select wisely among all these convolution implementations, which is, annoying for users. Good news is that the next release of CUDNN will include such smart selection and Minerva will be one of the first tier who support that. So please be patient for our next release.

- Minjie
