### ISSUE TITLE
Does Owl trainer randomly shuffle data in each epoch?

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#36]
If yes, how does it shuffle data for very large datasets (e.g. ImageNet)?

**Comment by sneakerkg** [comment]
Hi Zer0n,

We shuffle data offline. For ImageNet, we shuffle the data when packing image into lmdb.

We are implementing new IO, there're two features: 1. Pseudo-shuffling, load part of the data and shuffle within the part; 2. More compact data format that allow us load all the ImageNet into memory, and then shuffle in the memory;

We'll inform you when the new function is OK.

Thanks,
Tianjun

**Comment by zer0n** [comment]
Got it. Thanks.
