### ISSUE TITLE
Missing index 0 in CPU SoftmaxForward

### ISSUE THREAD

**Issue by lovi9573** [dmlc/minerva#40]
The Cpu implementation of SoftmaxForward in /minerva/op/impl/basic.cpp misses the 0 index in the second (line 249) and third (line 255) loops.

**Comment by hotpxl** [comment]
Thanks! I'll take a look at it.

**Comment by hotpxl** [comment]
Thanks! The bug is confirmed and fixed. I'll notify another developer to ensure we make it right this time.
