### ISSUE TITLE
broadcasting NArray + NArray

### ISSUE THREAD

**Issue by lukemetz** [dmlc/minerva#45]
Hello. First, thanks for the really cool library!

I am experiencing odd issues with broadcasting when doing element wise operations between two arrays. I would expect all of the following to work but not all of them do.

```
owl.zeros((3,3)) + 10 # works
owl.zeros((3,3)) + np.array(10) # works
owl.zeros((3,3)) + np.array([10]) # works
owl.zeros((3,3)) + np.array([[10]]) # works


owl.zeros((3,3)) + owl.from_numpy(np.array([[10]])) # Fails

what():  [22:31:13] /home/luke/Apps/minerva/minerva/op/impl/cuda.cpp:223: Check failed: (closure.dims_to_replicate.NumDims()) == (1) currently do norm on one dimension only

owl.zeros((3,3)) + owl.from_numpy(np.array(10)) # Fails

*** RuntimeError: [22:32:19] /home/luke/Apps/minerva/minerva/narray/narray.cpp:197: Check failed: (lhs.Size().NumDims()) == (rhs.Size().NumDims()) #dimension mismatch
```

It appears that broadcasting does not work between two owl arrays. Is this correct? Is there a way to work around this?

Thanks!

**Comment by hjk41** [comment]
try owl.zeros((3,3)) + owl.from_numpy(np.array([[10, 10, 10]]))

That's a constrain of Minerva's norm implementation. It requires both
NArray to have the same number of dimensions, and the one broadcasted
should have N-1 non-zero dimensions.

On Thu, Aug 6, 2015 at 10:34 AM, Luke notifications@github.com wrote:

> Hello. First, thanks for the really cool library!
> 
> I am experiencing odd issues with broadcasting when doing element wise
> operations between two arrays. I would expect all of the following to work
> but not all of them do.
> 
> owl.zeros((3,3)) + 10 # works
> owl.zeros((3,3)) + np.array(10) # works
> owl.zeros((3,3)) + np.array([10]) # works
> owl.zeros((3,3)) + np.array([[10]]) # works
> 
> owl.zeros((3,3)) + owl.from_numpy(np.array([[10]])) # Fails
> 
> what():  [22:31:13] /home/luke/Apps/minerva/minerva/op/impl/cuda.cpp:223: Check failed: (closure.dims_to_replicate.NumDims()) == (1) currently do norm on one dimension only
> 
> owl.zeros((3,3)) + owl.from_numpy(np.array(10)) # Fails
> 
> **\* RuntimeError: [22:32:19] /home/luke/Apps/minerva/minerva/narray/narray.cpp:197: Check failed: (lhs.Size().NumDims()) == (rhs.Size().NumDims()) #dimension mismatch
> 
> It appears that broadcasting does not work between two owl arrays. Is this
> correct? Is there a way to work around this?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dmlc/minerva/issues/45.

## 

HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by lukemetz** [comment]
Sweet. Thanks for the info.
