### ISSUE TITLE
use_dag flag 

### ISSUE THREAD

**Issue by lukemetz** [dmlc/minerva#47]
Hello,
I am experiencing a crash when trying to launch without the dag from python.

```
$ python tt.py --use_dag=false
[22:16:29] /home/luke/Repos/minerva/minerva/system/minerva_system.cpp:89: dag engine disabled
*** Error in `python': free(): invalid pointer: 0x000000000102a498 ***
Aborted (core dumped)
```

I tracked it back to:
https://github.com/dmlc/minerva/blob/master/owl/owl/libowl.pyx#L46
where argv is being freed.

Commenting that out does fix the problem but most likely leaks.

I am running from ubuntu 15.04, building with CPU only. with no flags launches without an issue.

Thanks!

**Comment by hotpxl** [comment]
Looks like `gflags` is modifying the pointer `argv`.

Thanks for reporting this issue.
