### ISSUE TITLE
Differences with MShadow

### ISSUE THREAD

**Issue by knsong** [dmlc/minerva#55]
hi, all
    what's the difference between MShadow and minerva? From the documents, I know that both of them can perform tensor operations of unified form on both CPU and GPU. And their languages are both C++. So I'm wondering what's the main difference between them?

**Comment by jermainewang** [comment]
Hi Dale,

First of all, Minerva is not being supported right now. You could try use
MXNet https://github.com/dmlc/mxnet or Minpy
https://github.com/dmlc/minpy (a numpy-frontend built on MXNet). For your
question, they are of different level. MShadow is a pure tensor library
that provides basic tensor operations on CPU/GPU. You could think about
math library in c. On the other hand, systems like Minerva/MXNet are in
higher level, which provide semantics for neural network training,
multi-GPU/machine training, I/O, etc. In fact, MXNet relies on MShadow as
its core tensor library.

Best,
Minjie
​

On Mon, Jun 13, 2016 at 2:54 AM, Dale notifications@github.com wrote:

> hi, all
> what's the difference between MShadow and minerva? From the documents, I
> know that both of them can perform tensor operations of unified form on
> both CPU and GPU. And their languages are both C++. So I'm wondering what's
> the main difference between them?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/dmlc/minerva/issues/55, or mute the thread
> https://github.com/notifications/unsubscribe/AD3qZe_I9Q_HQ5eZzqXR68A2ALUYbSqaks5qLSjOgaJpZM4I0Kn-
> .

## 

Minjie Wang
_New York University | Computer Science_
715 Broadway, New York, NY, 10009

**Comment by knsong** [comment]
@jermainewang Thanks a lot! That makes me much clearer about them.
